version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/1.sql
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    container_name: la-vie-db

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODEJS_LOCAL_PORT:$NODEJS_DOCKER_PORT
    volumes: 
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    container_name: la-vie-api

volumes: 
  db-config:
  db-data: